version: '3'

services:
    db:
        image: "mariadb:10.2.16"
        ports:
            - 3002:3306
        environment:
            MYSQL_DATABASE: eta
            MYSQL_USER: arkiv
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    rabbitmq:
        image: "rabbitmq:latest"
        ports:
            - 15002:5672
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
    redis:
        image: "redis:latest"
        ports:
            - 6002:6379

    elasticsearch:
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        ports:
            - "9202:9200"
            - "9302:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk

    logstash:
        build:
            context: logstash/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
            - "5002:5000"
            - "9602:9600"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk
        depends_on:
            - elasticsearch

    kibana:
        build:
            context: kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5602:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch

networks:
    elk:
        driver: bridge
